# site settings
title: Chris Lawson
subtitle: Computer Engineering Undergrad at Cal Poly SLO
description: Cal Poly SLO Undergrad studying Computer Engineering. Class of 2024.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://chrislawson.dev # the base hostname & protocol for your site
author: Chris Lawson
google_analytics: UA-131464362-1

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"

# social settings
email: contact@chrislawson.dev
facebook_url: https://www.facebook.com/chris.lawson.75839923
instagram_url: https://www.instagram.com/chris2fourlaw
snapchat_url: https://www.snapchat.com/add/chris2fourlaw
github_url: https://github.com/Chris2fourlaw
linkedin_url: https://www.linkedin.com/in/christopher-lawson-746265182/
spotify_url: https://open.spotify.com/user/chris2fourlaw

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
