# site settings
title: Chris Lawson
subtitle: SDE at Amazon
description: Software Development Engineer at Amazon, Computer Science graduate from Cal Poly SLO.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://chrislawson.dev # the base hostname & protocol for your site
author: Chris Lawson
google_analytics: UA-131464362-1

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"

# social settings
github_url: https://github.com/cjlawson02
linkedin_url: https://www.linkedin.com/in/christopher-lawson-746265182/
spotify_url: https://open.spotify.com/user/chris2fourlaw

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
